{{- if .Values.needETCD -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd
spec:
  clusterIP: None
  ports:
  - name: etcd-2379
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: etcd-2380
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    app: etcd
  type: ClusterIP
{{- end}}